//! The editable source of a track: roads as splines with their cross-sections, barriers,
//! markers for the race layout, surfaces and materials. Stored as `project.ron` in the
//! project's directory, next to the textures it uses.
//!
//! Positions are in the simulation's world frame (m, Z up). Places along a road are
//! given as spline parameters `u` (node index plus the fraction of the way to the next
//! node), so that they stay with the road's shape when nodes move. Roads, surfaces and
//! materials refer to each other by name, so the file reads (and can be written) on
//! its own.

use std::path::{Path, PathBuf};

use glam::{DVec2, DVec3};
use open_racing_sim::{Surface, SurfaceProps};
use serde::{Deserialize, Serialize};

use crate::Error;

/// Version of `project.ron`.
pub const FORMAT_VERSION: u32 = 2;
pub const PROJECT_FILE: &str = "project.ron";

/// Name of an entry of `Project::surfaces`.
pub type SurfaceId = String;
/// Name of an entry of `Project::materials`.
pub type MaterialId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    pub format: u32,
    pub name: String,
    pub surfaces: Vec<NamedSurface>,
    pub materials: Vec<MaterialDef>,
    pub roads: Vec<Road>,
    /// Kerbs, walls and fences placed on their own, apart from any road.
    #[serde(default)]
    pub splines: Vec<Spline>,
    /// 3D models placed in the scene: grandstands, signs, trees, buildings.
    #[serde(default)]
    pub props: Vec<Prop>,
    /// Kinds of kerbs, gravel traps and verges to lay.
    #[serde(default = "crate::builtin::strip_styles")]
    pub strip_styles: Vec<StripStyle>,
    /// Kinds of walls, rails, fences and tyre stacks to put up.
    #[serde(default = "crate::builtin::wall_styles")]
    pub wall_styles: Vec<WallStyle>,
    /// Name of the circuit: the closed road the centreline, timing and grid follow.
    pub main_road: String,
    pub markers: Markers,
    pub terrain: Terrain,
    /// Where the project's (0, 0) lies on the Earth, once a real place was brought in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo: Option<crate::geo::Geo>,
    /// A picture of the real place (a satellite image, a track map) laid flat in the
    /// editor to trace the roads over. Not part of the track.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference: Option<Reference>,
}

/// An image laid flat over the ground in the editor, for tracing a real circuit.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reference {
    /// A PNG, JPEG or DDS, relative to the project's directory.
    pub image: PathBuf,
    /// Where the image's middle lies, m.
    pub center: DVec2,
    /// How wide the image is on the ground, m; its height follows its aspect.
    pub width: f64,
    /// Turn anticlockwise seen from above, radians.
    #[serde(default)]
    pub rotation: f64,
    /// Height it is drawn at, m.
    #[serde(default)]
    pub height: f64,
    /// 0 (invisible) to 1 (opaque).
    #[serde(default = "one")]
    pub opacity: f64,
    #[serde(default = "yes")]
    pub visible: bool,
}

/// Physical properties of a surface, with a name for the editor.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamedSurface {
    pub name: String,
    pub props: SurfaceProps,
}

/// A tiled, tinted texture with dielectric PBR parameters.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterialDef {
    pub name: String,
    /// sRGB tint multiplied with the texture.
    pub color: [f32; 3],
    pub texture: TextureSource,
    /// Metres one repetition of the texture covers: across and along a road.
    pub tile: [f32; 2],
    pub roughness: f32,
    pub reflectance: f32,
    /// Render back faces too (thin barriers and fences).
    #[serde(default)]
    pub double_sided: bool,
    /// A tangent-space normal map, tiled as the texture.
    #[serde(default)]
    pub normal: TextureSource,
    /// What the texture's alpha does.
    #[serde(default)]
    pub alpha: Alpha,
}

/// How a material's alpha is used.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub enum Alpha {
    /// Ignored.
    #[default]
    Opaque,
    /// Cut out below this value, as for fences and foliage.
    Mask(f32),
    /// Blended, as for glass.
    Blend,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TextureSource {
    /// Plain colour.
    #[default]
    None,
    /// A texture generated by the tool.
    Builtin(BuiltinTexture),
    /// A PNG, JPEG or DDS file, relative to the project's directory.
    File(PathBuf),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuiltinTexture {
    Asphalt,
    /// Red and white blocks along the kerb, one pair per repetition.
    Kerb,
    Grass,
    Gravel,
    Concrete,
    Armco,
    Paint,
    Dirt,
    /// Chain-link mesh, transparent between the wires (for `Alpha::Mask`).
    Fence,
    /// Stacked tyres seen from the side.
    Tyres,
}

impl BuiltinTexture {
    pub const ALL: [Self; 10] = [
        Self::Asphalt,
        Self::Kerb,
        Self::Grass,
        Self::Gravel,
        Self::Concrete,
        Self::Armco,
        Self::Paint,
        Self::Dirt,
        Self::Fence,
        Self::Tyres,
    ];
}

/// How the two Bézier handles at a node relate to one another.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum HandleMode {
    #[default]
    Auto,
    /// Opposite directions, with independently adjustable lengths.
    Aligned,
    /// Independently adjustable directions and lengths.
    Free,
}

/// The two handles of a road or spline node.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub enum NodeHandles {
    #[default]
    Auto,
    Aligned {
        outgoing: DVec3,
        incoming_length: f64,
    },
    Free {
        incoming: DVec3,
        outgoing: DVec3,
    },
}

impl NodeHandles {
    pub fn is_auto(&self) -> bool {
        matches!(self, Self::Auto)
    }

    pub fn mode(self) -> HandleMode {
        match self {
            Self::Auto => HandleMode::Auto,
            Self::Aligned { .. } => HandleMode::Aligned,
            Self::Free { .. } => HandleMode::Free,
        }
    }

    /// The handles with their offsets put through `f`, a turn or a scaling of the node's
    /// surroundings; automatic ones follow by themselves.
    pub fn map(self, f: impl Fn(DVec3) -> DVec3) -> Self {
        match self {
            Self::Auto => Self::Auto,
            Self::Aligned {
                outgoing,
                incoming_length,
            } => Self::Aligned {
                outgoing: f(outgoing),
                incoming_length: f(-outgoing.normalize_or_zero() * incoming_length).length(),
            },
            Self::Free { incoming, outgoing } => Self::Free {
                incoming: f(incoming),
                outgoing: f(outgoing),
            },
        }
    }

    /// The mode and both offsets, as `Op::SetNodeHandles` takes them; zero for
    /// automatic handles.
    pub fn offsets(self) -> (HandleMode, DVec3, DVec3) {
        match self {
            Self::Auto => (HandleMode::Auto, DVec3::ZERO, DVec3::ZERO),
            Self::Aligned {
                outgoing,
                incoming_length,
            } => (
                HandleMode::Aligned,
                -outgoing.normalize_or_zero() * incoming_length,
                outgoing,
            ),
            Self::Free { incoming, outgoing } => (HandleMode::Free, incoming, outgoing),
        }
    }

    /// The handles reversed, for a line driven the other way: incoming and outgoing
    /// swap.
    pub fn reversed(self) -> Self {
        match self {
            Self::Auto => Self::Auto,
            Self::Aligned {
                outgoing,
                incoming_length,
            } => Self::Aligned {
                outgoing: -outgoing.normalize_or_zero() * incoming_length,
                incoming_length: outgoing.length(),
            },
            Self::Free { incoming, outgoing } => Self::Free {
                incoming: outgoing,
                outgoing: incoming,
            },
        }
    }

    pub fn from_offsets(mode: HandleMode, incoming: DVec3, outgoing: DVec3) -> Self {
        match mode {
            HandleMode::Auto => Self::Auto,
            HandleMode::Aligned => Self::Aligned {
                outgoing,
                incoming_length: incoming.length(),
            },
            HandleMode::Free => Self::Free { incoming, outgoing },
        }
    }

    pub fn is_valid(self) -> bool {
        match self {
            Self::Auto => true,
            Self::Aligned {
                outgoing,
                incoming_length,
            } => {
                outgoing.is_finite()
                    && incoming_length.is_finite()
                    && incoming_length >= 0.0
                    && (outgoing.length_squared() > 1e-12 || incoming_length == 0.0)
            }
            Self::Free { incoming, outgoing } => incoming.is_finite() && outgoing.is_finite(),
        }
    }
}

/// A control point of a road or spline.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    pub pos: DVec3,
    #[serde(default, skip_serializing_if = "NodeHandles::is_auto")]
    pub handles: NodeHandles,
}

impl Node {
    pub fn new(pos: DVec3) -> Self {
        Self {
            pos,
            handles: NodeHandles::Auto,
        }
    }

    pub fn at(x: f64, y: f64, z: f64) -> Self {
        Self::new(DVec3::new(x, y, z))
    }
}

/// A value that varies along a road: keys at spline parameters, eased between them. A
/// closed road's value eases from the last key round to the first.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationCurve {
    pub keys: Vec<Key>,
}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Key {
    pub u: f64,
    pub value: f64,
    /// Value change per unit of spline parameter on either side of this key.
    #[serde(default)]
    pub slope_in: f64,
    #[serde(default)]
    pub slope_out: f64,
}

impl Key {
    pub fn new(u: f64, value: f64) -> Self {
        Self {
            u,
            value,
            slope_in: 0.0,
            slope_out: 0.0,
        }
    }
}

impl StationCurve {
    pub fn constant(value: f64) -> Self {
        Self {
            keys: vec![Key::new(0.0, value)],
        }
    }

    /// The value at `u` on a road whose parameter runs over [0, `period`); closed roads
    /// wrap round, open ones hold their end values.
    pub fn eval(&self, u: f64, period: f64, closed: bool) -> f64 {
        let keys = &self.keys;
        let Some(first) = keys.first() else {
            return 0.0;
        };
        if keys.len() == 1 {
            return first.value;
        }
        // Keys are kept sorted by `u`.
        let last = keys[keys.len() - 1];
        let ease = |a: &Key, b: &Key, u: f64, span: f64| {
            let t = if span > 0.0 {
                (u / span).clamp(0.0, 1.0)
            } else {
                0.0
            };
            let (m0, m1) = (a.slope_out, b.slope_in);
            if m0 == 0.0 && m1 == 0.0 {
                return a.value + (b.value - a.value) * t * t * (3.0 - 2.0 * t);
            }
            let t2 = t * t;
            let t3 = t2 * t;
            (2.0 * t3 - 3.0 * t2 + 1.0) * a.value
                + (t3 - 2.0 * t2 + t) * span * m0
                + (-2.0 * t3 + 3.0 * t2) * b.value
                + (t3 - t2) * span * m1
        };
        if u < first.u || u >= last.u {
            if !closed {
                return if u < first.u { first.value } else { last.value };
            }
            let span = first.u + period - last.u;
            let from = if u >= last.u {
                u - last.u
            } else {
                u + period - last.u
            };
            return ease(&last, first, from, span);
        }
        let i = keys.partition_point(|k| k.u <= u) - 1;
        let (a, b) = (&keys[i], &keys[i + 1]);
        ease(a, b, u - a.u, b.u - a.u)
    }

    /// Sets the value at `u`, adding a key or moving the one already there.
    pub fn set(&mut self, u: f64, value: f64) {
        match self.keys.iter_mut().find(|k| (k.u - u).abs() < 1e-6) {
            Some(k) => k.value = value,
            None => {
                self.keys.push(Key::new(u, value));
                self.keys.sort_by(|a, b| a.u.total_cmp(&b.u));
            }
        }
    }
}

/// A stretch of road between two spline parameters. On a closed road `from > to` wraps
/// through the start.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Range {
    pub from: f64,
    pub to: f64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Side {
    Left,
    Right,
}

impl Side {
    /// +1 to the left, −1 to the right.
    pub fn sign(self) -> f64 {
        match self {
            Self::Left => 1.0,
            Self::Right => -1.0,
        }
    }

    pub fn other(self) -> Self {
        match self {
            Self::Left => Self::Right,
            Self::Right => Self::Left,
        }
    }
}

/// Cross-section shape of a strip, from its inner to its outer edge.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum Profile {
    /// Continues the plane of what is inside it.
    Flat,
    /// A rounded crown this high (m) in the middle, as on a kerb.
    Crown(f64),
    /// Falls (or rises, negative) this far (m) to the outer edge.
    Slope(f64),
    /// Any shape: heights (m) at fractions (0 to 1) of the way across, in order, joined
    /// by straight lines; before the first and after the last, their heights. A
    /// stepped, saw-tooth or double-hump kerb.
    Shape(Vec<[f64; 2]>),
}

impl Profile {
    /// Height above its inner edge at `x` of the way across.
    pub fn height(&self, x: f64) -> f64 {
        match self {
            Profile::Flat => 0.0,
            Profile::Crown(h) => h * (std::f64::consts::PI * x).sin(),
            Profile::Slope(drop) => -drop * x,
            Profile::Shape(points) => {
                let i = points.partition_point(|p| p[0] <= x);
                match (points.get(i.wrapping_sub(1)), points.get(i)) {
                    (Some(a), Some(b)) if b[0] - a[0] > 1e-9 => {
                        a[1] + (b[1] - a[1]) * (x - a[0]) / (b[0] - a[0])
                    }
                    (Some(a), _) => a[1],
                    (None, Some(b)) => b[1],
                    (None, None) => 0.0,
                }
            }
        }
    }
}

/// A band alongside the road: kerb, run-off, gravel trap, grass verge.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Strip {
    pub name: String,
    pub width: f64,
    pub surface: SurfaceId,
    pub material: MaterialId,
    pub profile: Profile,
    /// Where the strip is; everywhere when empty.
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// Metres over which it narrows to nothing at the ends of its ranges.
    #[serde(default)]
    pub fade: f64,
    /// The strip type it was made from: changing the type changes it too.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// The corner it was laid round, which keeps it there as the road changes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corner: Option<Anchor>,
}

/// A kind of kerb, gravel trap, run-off or verge, made once and laid anywhere: along a
/// road, round its corners, or on a spline of its own.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StripStyle {
    pub name: String,
    /// Width it is laid at; each strip may be made wider or narrower.
    pub width: f64,
    pub profile: Profile,
    pub surface: SurfaceId,
    pub material: MaterialId,
    /// Metres over which it narrows to nothing at the ends of its stretches.
    #[serde(default)]
    pub fade: f64,
}

/// A kind of wall, guard rail, fence or tyre stack, made once and put along roads and
/// splines.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WallStyle {
    pub name: String,
    pub height: f64,
    /// 0 for a thin rail or fence.
    pub thickness: f64,
    pub material: MaterialId,
    /// A model repeated along it instead of its plain shape.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelRun>,
}

impl StripStyle {
    /// A strip of this type.
    pub fn strip(&self, name: &str, ranges: Vec<Range>) -> Strip {
        Strip {
            name: name.to_string(),
            width: self.width,
            surface: self.surface.clone(),
            material: self.material.clone(),
            profile: self.profile.clone(),
            ranges,
            fade: self.fade,
            style: Some(self.name.clone()),
            corner: None,
        }
    }

    /// Gives a strip of this type its look and feel; its width stays its own.
    pub fn restyle(&self, s: &mut Strip) {
        s.surface = self.surface.clone();
        s.material = self.material.clone();
        s.profile = self.profile.clone();
        s.fade = self.fade;
        s.style = Some(self.name.clone());
    }
}

impl WallStyle {
    /// A barrier of this type.
    pub fn barrier(&self, name: &str, side: Side, offset: f64, ranges: Vec<Range>) -> Barrier {
        let mut b = Barrier {
            name: name.to_string(),
            side,
            offset,
            height: 0.0,
            thickness: 0.0,
            material: String::new(),
            ranges,
            model: None,
            style: None,
            corner: None,
        };
        self.restyle(&mut b);
        b
    }

    /// Gives a barrier of this type its shape and look; its place stays its own.
    pub fn restyle(&self, b: &mut Barrier) {
        b.height = self.height;
        b.thickness = self.thickness;
        b.material = self.material.clone();
        b.model = self.model.clone();
        b.style = Some(self.name.clone());
    }
}

/// A 3D model repeated along a wall in place of its plain shape: a tyre stack, a
/// section of guard rail, a fence panel. The model's +X runs along the wall, its +Z is
/// up and its +Y faces the road (a spline's left); its origin sits on the wall's line.
/// Cars still collide with the wall's plain shape.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelRun {
    /// A glTF file (.glb or .gltf), relative to the project's directory.
    pub model: PathBuf,
    /// Length of each copy along the wall, m; 0 takes the model's own. Copies stretch a
    /// little so that a whole number of them fill each stretch.
    #[serde(default)]
    pub length: f64,
    /// Bend each copy along the line (else each stands straight, on its middle).
    #[serde(default = "yes")]
    pub bend: bool,
    /// Turn it round, facing away from the road.
    #[serde(default)]
    pub flip: bool,
}

/// Which part of a corner a strip or barrier laid round it is.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CornerPart {
    /// On the outside where cars turn in.
    Entry,
    /// On the inside round the apex.
    Apex,
    /// On the outside where cars run out.
    Exit,
    /// The whole outside, from before the entry to well past the exit: a gravel trap,
    /// run-off, a tyre wall.
    Outside,
}

impl CornerPart {
    pub const ALL: [CornerPart; 4] = [
        CornerPart::Entry,
        CornerPart::Apex,
        CornerPart::Exit,
        CornerPart::Outside,
    ];

    pub fn label(self) -> &'static str {
        match self {
            CornerPart::Entry => "entry",
            CornerPart::Apex => "apex",
            CornerPart::Exit => "exit",
            CornerPart::Outside => "outside",
        }
    }
}

/// Where a strip or barrier was laid round a corner, found again however the road's
/// corners are renumbered, and refitted when its shape changes.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Anchor {
    pub part: CornerPart,
    /// Where the corner turned tightest when it was last fitted, as a spline parameter.
    pub apex: f64,
    /// Metres its start and end lie beyond the part's usual place round the corner,
    /// positive further along the road.
    #[serde(default)]
    pub shift: [f64; 2],
}

/// A painted line on the road, drawn only: it does not change the surface.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaintLine {
    pub name: String,
    /// Lateral offset of its middle from the road's centre, m, positive to the left.
    pub offset: f64,
    pub width: f64,
    pub material: MaterialId,
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// Painted and gap lengths of a dashed line, m.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dash: Option<(f64, f64)>,
}

/// A mark painted across a road: a start/finish line, a grid slot, a pit lane's
/// speed limit line. Drawn only.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mark {
    pub name: String,
    /// Where its middle is along the road, as a spline parameter.
    pub at: f64,
    /// How long it is along the road, m.
    pub length: f64,
    /// Where it runs across, m from the road's centre, positive to the left: from its
    /// right end to its left.
    pub from: f64,
    pub to: f64,
    pub material: MaterialId,
}

/// Copies of a model beside a road, every `spacing` metres along its stretches or at
/// given places: trees, cones, marker boards, lamp posts, spectators' stands, pit
/// garages. Each faces the road (the model's +X along it, +Y towards it).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropRow {
    pub name: String,
    /// A glTF file (.glb or .gltf), relative to the project's directory.
    pub model: PathBuf,
    pub side: Side,
    /// Distance from the road's edge, m.
    pub offset: f64,
    /// Metres between copies.
    pub spacing: f64,
    /// Where it runs; everywhere when empty.
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// Places along the road (`u`) for one copy each, instead of every `spacing`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub at: Vec<f64>,
    /// Turn from facing the road, radians anticlockwise seen from above.
    #[serde(default)]
    pub yaw: f64,
    #[serde(default = "one")]
    pub scale: f64,
    /// How much copies differ, at random but the same every build.
    #[serde(default, skip_serializing_if = "Jitter::is_none")]
    pub jitter: Jitter,
    /// Stand each on the ground under it (else at the road's height).
    #[serde(default = "yes")]
    pub drape: bool,
    /// Whether cars collide with them.
    #[serde(default)]
    pub collide: bool,
}

/// How much the copies of a row differ from each other: up to this far across (m),
/// turned (radians) and resized (a fraction), either way.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Jitter {
    #[serde(default)]
    pub offset: f64,
    #[serde(default)]
    pub yaw: f64,
    #[serde(default)]
    pub scale: f64,
}

impl Jitter {
    pub fn is_none(&self) -> bool {
        *self == Self::default()
    }
}

/// A wall, guard rail or fence the cars collide with.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Barrier {
    pub name: String,
    pub side: Side,
    /// Distance from the road's edge, m.
    pub offset: f64,
    pub height: f64,
    /// 0 for a thin rail or fence.
    pub thickness: f64,
    pub material: MaterialId,
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// A model repeated along it instead of its plain shape.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelRun>,
    /// The wall type it was made from: changing the type changes it too.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// The corner it was put round, which keeps it there as the road changes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corner: Option<Anchor>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Road {
    pub name: String,
    pub closed: bool,
    pub nodes: Vec<Node>,
    /// Distances from the road's centre to its edges, m.
    pub width_left: StationCurve,
    pub width_right: StationCurve,
    /// Banking in radians; positive raises the right edge, as for a left-hand corner.
    pub bank: StationCurve,
    /// Height of the road's centre above its edges, m, for drainage.
    pub crown: f64,
    pub surface: SurfaceId,
    pub material: MaterialId,
    /// Strips outside each edge, from the road outwards.
    pub left: Vec<Strip>,
    pub right: Vec<Strip>,
    pub lines: Vec<PaintLine>,
    pub barriers: Vec<Barrier>,
    /// Marks painted across it: the start line, grid slots, pit lane lines.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub marks: Vec<Mark>,
    /// Models repeated beside it: trees, cones, boards, lights, stands, garages.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rows: Vec<PropRow>,
    /// Spacing of the cross-sections the road is built from, m.
    pub resolution: f64,
}

impl Road {
    /// Number of spline segments.
    pub fn segments(&self) -> usize {
        crate::curve::segments(self.nodes.len(), self.closed)
    }

    /// Range of the spline parameter: [0, period].
    pub fn period(&self) -> f64 {
        self.segments() as f64
    }

    pub fn strips(&self, side: Side) -> &Vec<Strip> {
        match side {
            Side::Left => &self.left,
            Side::Right => &self.right,
        }
    }

    pub fn strips_mut(&mut self, side: Side) -> &mut Vec<Strip> {
        match side {
            Side::Left => &mut self.left,
            Side::Right => &mut self.right,
        }
    }

    /// Whether any of its strips or barriers was laid round a corner.
    pub fn has_corner_parts(&self) -> bool {
        self.left
            .iter()
            .chain(&self.right)
            .any(|s| s.corner.is_some())
            || self.barriers.iter().any(|b| b.corner.is_some())
    }

    /// Inserts a node before `index`, keeping keys, ranges and corner anchors where
    /// they were on the road. Gives what became of the road's spline parameters, for
    /// the markers on it.
    pub fn insert_node(&mut self, index: usize, node: Node) -> impl Fn(f64) -> f64 + use<> {
        let f = inserted(&self.nodes, self.closed, index, node.pos);
        self.nodes.insert(index, node);
        self.map_params(&f);
        f
    }

    /// Removes a node, keeping keys, ranges and corner anchors where they were on the
    /// road as far as possible. Gives what became of the road's spline parameters.
    pub fn remove_node(&mut self, index: usize) -> impl Fn(f64) -> f64 + use<> {
        let f = removed(&self.nodes, self.closed, index);
        self.nodes.remove(index);
        self.map_params(&f);
        f
    }

    /// Splits segment `i` in two at its middle with a node that keeps the road's shape,
    /// and what lay on the segment on the same places. Gives what became of the road's
    /// spline parameters.
    pub fn split_segment(&mut self, i: usize) -> impl Fn(f64) -> f64 + use<> {
        self.nodes = split_segment(&self.nodes, self.closed, i);
        let i = i as f64;
        let f = move |u: f64| {
            if u <= i {
                u
            } else if u < i + 1.0 {
                i + 2.0 * (u - i)
            } else {
                u + 1.0
            }
        };
        self.map_params(&f);
        f
    }

    /// Puts every spline parameter of the road through `f`: its profiles' keys, its
    /// parts' stretches, its marks and the apexes its corner parts were laid round.
    pub fn map_params(&mut self, f: &impl Fn(f64) -> f64) {
        for c in [&mut self.width_left, &mut self.width_right, &mut self.bank] {
            c.keys.iter_mut().for_each(|k| k.u = f(k.u));
            c.keys.sort_by(|a, b| a.u.total_cmp(&b.u));
        }
        let ranges = self
            .left
            .iter_mut()
            .chain(self.right.iter_mut())
            .flat_map(|s| s.ranges.iter_mut())
            .chain(self.barriers.iter_mut().flat_map(|b| b.ranges.iter_mut()))
            .chain(self.lines.iter_mut().flat_map(|l| l.ranges.iter_mut()));
        for r in ranges {
            r.from = f(r.from);
            r.to = f(r.to);
        }
        for m in &mut self.marks {
            m.at = f(m.at);
        }
        for r in &mut self.rows {
            for g in &mut r.ranges {
                g.from = f(g.from);
                g.to = f(g.to);
            }
            r.at.iter_mut().for_each(|u| *u = f(*u));
        }
        let anchors = self
            .left
            .iter_mut()
            .chain(self.right.iter_mut())
            .filter_map(|s| s.corner.as_mut())
            .chain(self.barriers.iter_mut().filter_map(|b| b.corner.as_mut()));
        for a in anchors {
            a.apex = f(a.apex);
        }
    }
}

/// A map of a line's old spline parameters to its new ones, from where each old
/// segment's stretch goes: `segment(m, f)` for the fraction `f` along segment `m`.
fn remap(
    segments: usize,
    closed: bool,
    segment: impl Fn(usize, f64) -> f64,
) -> impl Fn(f64) -> f64 {
    move |u: f64| {
        if segments == 0 {
            return u;
        }
        let end = segments as f64;
        let u = if closed && u >= end {
            // The end of a stretch running to the loop's end stays there.
            return segment(segments - 1, 1.0);
        } else if closed {
            u.rem_euclid(end)
        } else {
            u.clamp(0.0, end)
        };
        let m = (u.floor() as usize).min(segments - 1);
        segment(m, u - m as f64)
    }
}

/// How far along segment `i` of a line, as a fraction, it passes nearest to `p`.
fn nearest_along(nodes: &[Node], closed: bool, i: usize, p: DVec3) -> f64 {
    let c = crate::curve::segment(nodes, closed, i);
    let d = |t: f64| crate::curve::bezier(&c, t).distance_squared(p);
    let mut best = (0..=64)
        .map(|k| k as f64 / 64.0)
        .min_by(|a, b| d(*a).total_cmp(&d(*b)))
        .unwrap_or(0.5);
    let mut step = 1.0 / 64.0;
    for _ in 0..20 {
        step *= 0.5;
        for t in [best - step, best + step] {
            if (0.0..=1.0).contains(&t) && d(t) < d(best) {
                best = t;
            }
        }
    }
    best
}

/// What inserting a node at `pos` before node `index` does to a line's spline
/// parameters: the segment it splits divides where the node lies along it, and the
/// segments after it move on by one.
fn inserted(nodes: &[Node], closed: bool, index: usize, pos: DVec3) -> impl Fn(f64) -> f64 + use<> {
    let n = nodes.len();
    let split = if closed && n >= 2 {
        Some((index + n - 1) % n)
    } else if index > 0 && index < n {
        Some(index - 1)
    } else {
        None
    };
    let t = split.map_or(0.5, |i| {
        nearest_along(nodes, closed, i, pos).clamp(1e-3, 1.0 - 1e-3)
    });
    // Where old node `m` goes.
    let moved = move |m: usize| if m >= index { m + 1 } else { m } as f64;
    remap(crate::curve::segments(n, closed), closed, move |m, f| {
        if Some(m) != split {
            moved(m) + f
        } else if f < t {
            moved(m) + f / t
        } else {
            index as f64 + (f - t) / (1.0 - t)
        }
    })
}

/// What removing node `index` does to a line's spline parameters: the two segments
/// either side of it join into one, shared out by their lengths, and the segments after
/// it move back by one. A stretch on an open line's end segment that goes is kept at
/// the new end.
fn removed(nodes: &[Node], closed: bool, index: usize) -> impl Fn(f64) -> f64 + use<> {
    let n = nodes.len();
    let joined = if closed && n >= 3 {
        Some(((index + n - 1) % n, index))
    } else if index > 0 && index + 1 < n {
        Some((index - 1, index))
    } else {
        None
    };
    let length = |i: usize| {
        let c = crate::curve::segment(nodes, closed, i);
        (0..16)
            .map(|k| {
                let t = |k: usize| k as f64 / 16.0;
                crate::curve::bezier(&c, t(k)).distance(crate::curve::bezier(&c, t(k + 1)))
            })
            .sum::<f64>()
    };
    let share = joined.map_or(0.5, |(a, b)| {
        let (la, lb) = (length(a), length(b));
        if la + lb > 1e-9 { la / (la + lb) } else { 0.5 }
    });
    let moved = move |m: usize| if m > index { m - 1 } else { m } as f64;
    remap(
        crate::curve::segments(n, closed),
        closed,
        move |m, f| match joined {
            Some((a, _)) if m == a => moved(a) + f * share,
            Some((a, b)) if m == b => moved(a) + share + f * (1.0 - share),
            // An open line's first or last segment, gone with its end node.
            None if !closed && index == 0 && m == 0 => 0.0,
            None if !closed && index > 0 && m + 1 == index => moved(m),
            _ => moved(m) + f,
        },
    )
}

/// `nodes` with segment `i` split in two at its middle by a node that keeps the line's
/// shape (de Casteljau's construction). With automatic handles at both ends everything
/// stays automatic and the new node lies on the curve; otherwise both ends' handles are
/// made explicit as they are now, their halves into the segment halved, so that the
/// line keeps its shape exactly.
pub fn split_segment(nodes: &[Node], closed: bool, i: usize) -> Vec<Node> {
    let n = nodes.len();
    let j = (i + 1) % n;
    let [p0, p1, p2, p3] = crate::curve::segment(nodes, closed, i);
    let mid = crate::curve::bezier(&[p0, p1, p2, p3], 0.5);
    let mut out = nodes.to_vec();
    let node = if nodes[i].handles.is_auto() && nodes[j].handles.is_auto() {
        Node::new(mid)
    } else {
        let (a, b, c) = ((p0 + p1) * 0.5, (p1 + p2) * 0.5, (p2 + p3) * 0.5);
        let (ab, bc) = ((a + b) * 0.5, (b + c) * 0.5);
        let mut halve = |k: usize, outgoing_side: bool, offset: DVec3| {
            let (mut incoming, mut outgoing) = crate::curve::handles(nodes, closed, k);
            if outgoing_side {
                outgoing = offset;
            } else {
                incoming = offset;
            }
            let mode = match nodes[k].handles.mode() {
                HandleMode::Free => HandleMode::Free,
                HandleMode::Auto | HandleMode::Aligned => HandleMode::Aligned,
            };
            out[k].handles = NodeHandles::from_offsets(mode, incoming, outgoing);
        };
        halve(i, true, a - p0);
        halve(j, false, c - p3);
        Node {
            pos: mid,
            handles: NodeHandles::Aligned {
                outgoing: bc - mid,
                incoming_length: (ab - mid).length(),
            },
        }
    };
    out.insert(i + 1, node);
    out
}

/// Which side of its line a spline's band lies on, looking along the line.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum Align {
    #[default]
    Center,
    Left,
    Right,
}

/// What a spline is built into.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum Shape {
    /// A drivable band along the line: a kerb, a patch of run-off, a painted area.
    Band {
        width: f64,
        #[serde(default)]
        align: Align,
        /// Cross-section from its right edge to its left.
        profile: Profile,
        surface: SurfaceId,
        material: MaterialId,
        /// Height above the ground or the nodes, m, so that it shows over what is under.
        #[serde(default)]
        lift: f64,
    },
    /// A wall, guard rail or fence standing on the line.
    Wall {
        height: f64,
        /// 0 for a thin rail or fence.
        thickness: f64,
        material: MaterialId,
        /// Whether cars collide with it.
        #[serde(default = "yes")]
        collide: bool,
        /// A model repeated along it instead of its plain shape.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<ModelRun>,
    },
}

fn yes() -> bool {
    true
}

/// A kerb, wall or fence along its own spline, placed anywhere.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Spline {
    pub name: String,
    pub closed: bool,
    pub nodes: Vec<Node>,
    /// Follow the roads and the terrain under the line instead of the nodes' heights.
    pub drape: bool,
    pub shape: Shape,
    /// Spacing of the cross-sections it is built from, m.
    pub resolution: f64,
    /// The strip or wall type it was made from: changing the type changes it too.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
}

impl Spline {
    pub fn material(&self) -> &str {
        match &self.shape {
            Shape::Band { material, .. } | Shape::Wall { material, .. } => material,
        }
    }
}

/// A 3D model placed in the scene.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Prop {
    pub name: String,
    /// A glTF file (.glb or .gltf), relative to the project's directory.
    pub model: PathBuf,
    /// Where the model's origin goes.
    pub pos: DVec3,
    /// Turn about the vertical, radians, anticlockwise seen from above.
    #[serde(default)]
    pub yaw: f64,
    #[serde(default = "one")]
    pub scale: f64,
    /// Stand on the ground under `pos` instead of at its height.
    #[serde(default)]
    pub drape: bool,
    /// Whether cars collide with it.
    #[serde(default)]
    pub collide: bool,
}

fn one() -> f64 {
    1.0
}

/// Where a race is run: the start/finish line, sector boundaries, grid and pit lane.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Markers {
    /// Start/finish line on the main road.
    pub start: f64,
    /// Sector boundaries on the main road.
    pub sectors: Vec<f64>,
    pub grid: Grid,
    pub pit: Option<Pit>,
}

/// Grid slots generated behind the start line.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Grid {
    pub count: usize,
    /// Distance between consecutive slots, m.
    pub spacing: f64,
    /// Lateral offset of each slot from the middle, alternating sides, m.
    pub stagger: f64,
    /// Distance from the start line to the pole slot, m.
    pub behind: f64,
    /// Side of the pole slot.
    pub pole: Side,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pit {
    /// Name of the pit lane's road; it starts where the lane leaves the track and ends
    /// where it rejoins.
    pub road: String,
    /// Speed limit, m/s.
    pub speed_limit: f64,
    /// Pit boxes on the pit road.
    pub boxes: Vec<f64>,
    pub box_side: Side,
    /// Lateral offset of the boxes from the lane's centre, m.
    pub box_offset: f64,
}

/// Ground around the roads, shaped to meet their outer edges: level with them, or
/// following elevation data of the real place away from them, and shaped by landforms.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Terrain {
    pub enabled: bool,
    pub surface: SurfaceId,
    pub material: MaterialId,
    /// How far beyond the roads it extends, m.
    pub margin: f64,
    /// Size of its grid cells, m.
    pub cell: f64,
    /// Elevation data the ground away from the roads follows: a GeoTIFF, an ESRI ASCII
    /// grid or x y z points, relative to the project's directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub heights: Option<PathBuf>,
    /// Added to the elevation data's heights, m, to bring them to the roads'.
    #[serde(default)]
    pub heights_offset: f64,
    /// Hills, banks and hollows raised or dug, and level pads, away from the roads.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub landforms: Vec<Landform>,
}

/// A shape given to the ground away from the roads: round about `center`, or, with
/// `to`, stretched along the line from `center` to `to` (a spectators' bank along a
/// straight).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Landform {
    pub name: String,
    pub center: DVec2,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to: Option<DVec2>,
    /// Out to here it takes its full effect, m.
    pub radius: f64,
    /// Beyond `radius` it eases to nothing over this, m.
    pub falloff: f64,
    pub kind: LandformKind,
}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub enum LandformKind {
    /// Raises the ground this far, m; negative digs it.
    Raise(f64),
    /// Levels the ground at this height, m: a pad for a building or a car park.
    Level(f64),
}

impl Landform {
    /// How much of its effect it has at `p`: 1 within its radius, easing to 0 across
    /// its falloff.
    pub fn weight(&self, p: DVec2) -> f64 {
        let d = match self.to {
            Some(to) => {
                let ab = to - self.center;
                let t =
                    ((p - self.center).dot(ab) / ab.length_squared().max(1e-12)).clamp(0.0, 1.0);
                p.distance(self.center + ab * t)
            }
            None => p.distance(self.center),
        };
        if d <= self.radius {
            return 1.0;
        }
        if self.falloff <= 0.0 || d >= self.radius + self.falloff {
            return 0.0;
        }
        let t = 1.0 - (d - self.radius) / self.falloff;
        t * t * (3.0 - 2.0 * t)
    }
}

impl Project {
    /// A new project with the built-in surfaces and materials and a small oval to start
    /// from.
    pub fn new(name: &str) -> Self {
        let surfaces = crate::builtin::surfaces();
        let materials = crate::builtin::materials();
        let s = |name: &str| name.to_string();
        let m = s;
        // A rounded rectangle, 600 m × 250 m, driven anticlockwise.
        let nodes = [
            (0.0, 0.0),
            (250.0, 0.0),
            (420.0, 20.0),
            (480.0, 130.0),
            (420.0, 240.0),
            (250.0, 260.0),
            (0.0, 260.0),
            (-120.0, 200.0),
            (-150.0, 130.0),
            (-120.0, 60.0),
        ]
        .map(|(x, y)| Node::at(x, y, 0.0))
        .to_vec();
        // Kerbs through the corners.
        let corners = vec![Range { from: 1.6, to: 4.4 }, Range { from: 6.6, to: 9.4 }];
        let kerb = Strip {
            name: "kerb".into(),
            width: 1.2,
            surface: s("kerb"),
            material: m("kerb"),
            profile: Profile::Crown(0.03),
            ranges: corners,
            fade: 4.0,
            style: Some(s("kerb")),
            corner: None,
        };
        let grass = |width| Strip {
            name: "grass".into(),
            width,
            surface: s("grass"),
            material: m("grass"),
            profile: Profile::Slope(0.3),
            ranges: vec![],
            fade: 0.0,
            style: Some(s("grass")),
            corner: None,
        };
        let barrier = |side| Barrier {
            name: "wall".into(),
            side,
            offset: 20.0,
            height: 1.0,
            thickness: 0.5,
            material: m("concrete"),
            ranges: vec![],
            model: None,
            style: Some(s("concrete wall")),
            corner: None,
        };
        let road = Road {
            name: "circuit".into(),
            closed: true,
            nodes,
            width_left: StationCurve::constant(6.0),
            width_right: StationCurve::constant(6.0),
            bank: StationCurve::constant(0.0),
            crown: 0.05,
            surface: s("asphalt"),
            material: m("asphalt"),
            left: vec![kerb.clone(), grass(18.0)],
            right: vec![kerb, grass(18.0)],
            lines: [("left edge", 5.7), ("right edge", -5.7)]
                .map(|(name, offset)| PaintLine {
                    name: name.into(),
                    offset,
                    width: 0.12,
                    material: m("paint"),
                    ranges: vec![],
                    dash: None,
                })
                .to_vec(),
            barriers: vec![barrier(Side::Left), barrier(Side::Right)],
            marks: vec![],
            rows: vec![],
            resolution: 2.0,
        };
        Self {
            format: FORMAT_VERSION,
            name: name.into(),
            terrain: Terrain {
                enabled: true,
                surface: s("grass"),
                material: m("grass"),
                margin: 200.0,
                cell: 8.0,
                heights: None,
                heights_offset: 0.0,
                landforms: vec![],
            },
            surfaces,
            materials,
            roads: vec![road],
            splines: vec![],
            props: vec![],
            strip_styles: crate::builtin::strip_styles(),
            wall_styles: crate::builtin::wall_styles(),
            main_road: "circuit".into(),
            markers: Markers {
                start: 0.5,
                sectors: vec![3.0, 6.5],
                grid: Grid {
                    count: 12,
                    spacing: 8.0,
                    stagger: 2.5,
                    behind: 10.0,
                    pole: Side::Left,
                },
                pit: None,
            },
            reference: None,
            geo: None,
        }
    }

    pub fn load(dir: &Path) -> Result<Self, Error> {
        let path = dir.join(PROJECT_FILE);
        let src = std::fs::read_to_string(&path).map_err(|e| Error::Io(path.clone(), e))?;
        let project: Self =
            ron::from_str(&src).map_err(|e| Error::Parse(path.clone(), Box::new(e)))?;
        if project.format != FORMAT_VERSION {
            return Err(Error::Invalid(format!(
                "{}: format version {}, expected {FORMAT_VERSION}",
                path.display(),
                project.format
            )));
        }
        project.validate()?;
        Ok(project)
    }

    pub fn save(&self, dir: &Path) -> Result<(), Error> {
        std::fs::create_dir_all(dir).map_err(|e| Error::Io(dir.to_path_buf(), e))?;
        let src = ron::ser::to_string_pretty(self, ron::ser::PrettyConfig::default())
            .expect("project serialises");
        let path = dir.join(PROJECT_FILE);
        std::fs::write(&path, src).map_err(|e| Error::Io(path, e))
    }

    /// Checks that every name refers to something that exists and the main road can be
    /// a circuit.
    pub fn validate(&self) -> Result<(), Error> {
        let invalid = |msg: String| Err(Error::Invalid(msg));
        // The name is the package's directory under tracks/.
        let name = self.name.as_str();
        if name.trim().is_empty()
            || name != name.trim()
            || name == "."
            || name == ".."
            || name.contains(['/', '\\', ':', '*', '?', '"', '<', '>', '|'])
        {
            return invalid(format!(
                "the track name \"{name}\" must be usable as a folder name"
            ));
        }
        for (what, names) in [
            (
                "road or spline",
                self.roads
                    .iter()
                    .map(|r| &r.name)
                    .chain(self.splines.iter().map(|s| &s.name))
                    .collect::<Vec<_>>(),
            ),
            ("surface", self.surfaces.iter().map(|s| &s.name).collect()),
            ("prop", self.props.iter().map(|p| &p.name).collect()),
            ("material", self.materials.iter().map(|m| &m.name).collect()),
            (
                "strip type",
                self.strip_styles.iter().map(|s| &s.name).collect(),
            ),
            (
                "wall type",
                self.wall_styles.iter().map(|s| &s.name).collect(),
            ),
        ] {
            for (i, n) in names.iter().enumerate() {
                if names[..i].contains(n) {
                    return invalid(format!("two {what}s are named \"{n}\""));
                }
            }
        }
        let Some(main) = self.road(&self.main_road) else {
            return invalid(format!(
                "the main road \"{}\" does not exist",
                self.main_road
            ));
        };
        if !main.closed || main.nodes.len() < 3 {
            return invalid(format!(
                "the main road \"{}\" must be a closed loop of at least 3 nodes",
                main.name
            ));
        }
        for r in &self.roads {
            let strips = r.left.iter().chain(&r.right);
            let surfaces = std::iter::once(&r.surface).chain(strips.clone().map(|s| &s.surface));
            let materials = [&r.material]
                .into_iter()
                .chain(strips.map(|s| &s.material))
                .chain(r.lines.iter().map(|l| &l.material))
                .chain(r.barriers.iter().map(|b| &b.material))
                .chain(r.marks.iter().map(|m| &m.material));
            for s in surfaces {
                if self.surface_index(s).is_none() {
                    return invalid(format!("road \"{}\": no surface named \"{s}\"", r.name));
                }
            }
            for m in materials {
                if self.material_index(m).is_none() {
                    return invalid(format!("road \"{}\": no material named \"{m}\"", r.name));
                }
            }
            if r.nodes.len() < 2 {
                return invalid(format!("road \"{}\" needs at least 2 nodes", r.name));
            }
            if r.nodes
                .iter()
                .any(|n| !n.pos.is_finite() || !n.handles.is_valid())
            {
                return invalid(format!("road \"{}\": invalid node or handle", r.name));
            }
            for (name, curve) in [
                ("left width", &r.width_left),
                ("right width", &r.width_right),
                ("bank", &r.bank),
            ] {
                if curve.keys.is_empty()
                    || curve.keys.iter().any(|k| {
                        !k.u.is_finite()
                            || !k.value.is_finite()
                            || !k.slope_in.is_finite()
                            || !k.slope_out.is_finite()
                    })
                {
                    return invalid(format!("road \"{}\": {name} has an invalid key", r.name));
                }
            }
            if r.resolution < 0.25 {
                return invalid(format!("road \"{}\": resolution under 0.25 m", r.name));
            }
            if r.marks
                .iter()
                .any(|m| !(m.length > 0.0 && m.to > m.from && m.at.is_finite()))
            {
                return invalid(format!(
                    "road \"{}\": a mark needs a length and to run from right to left",
                    r.name
                ));
            }
            if r.left.iter().chain(&r.right).any(|s| s.width < 0.0) {
                return invalid(format!("road \"{}\": a strip has a negative width", r.name));
            }
            for side in [Side::Left, Side::Right] {
                let strips = r.strips(side);
                for (i, s) in strips.iter().enumerate() {
                    if strips[..i].iter().any(|t| t.name == s.name) {
                        return invalid(format!(
                            "road \"{}\": two strips on the {side:?} are named \"{}\"",
                            r.name, s.name
                        ));
                    }
                    self.check_strip_style(s.style.as_deref(), &s.profile)
                        .map_err(|e| Error::Invalid(format!("road \"{}\": {e}", r.name)))?;
                }
            }
            for b in &r.barriers {
                self.check_wall_style(b.style.as_deref(), b.model.as_ref())
                    .map_err(|e| Error::Invalid(format!("road \"{}\": {e}", r.name)))?;
            }
            for (i, row) in r.rows.iter().enumerate() {
                if r.rows[..i].iter().any(|o| o.name == row.name) {
                    return invalid(format!(
                        "road \"{}\": two rows are named \"{}\"",
                        r.name, row.name
                    ));
                }
                if !(row.spacing >= 0.5 || !row.at.is_empty())
                    || !(row.scale > 0.0)
                    || !row.offset.is_finite()
                    || !row.yaw.is_finite()
                {
                    return invalid(format!(
                        "road \"{}\": row \"{}\" needs a spacing of 0.5 m or more and a size above 0",
                        r.name, row.name
                    ));
                }
            }
        }
        for s in &self.strip_styles {
            self.check_strip_style(None, &s.profile)?;
            if self.surface_index(&s.surface).is_none()
                || self.material_index(&s.material).is_none()
            {
                return invalid(format!(
                    "strip type \"{}\": undefined surface or material",
                    s.name
                ));
            }
        }
        for s in &self.wall_styles {
            self.check_wall_style(None, s.model.as_ref())?;
            if self.material_index(&s.material).is_none() {
                return invalid(format!("wall type \"{}\": undefined material", s.name));
            }
        }
        for sp in &self.splines {
            let invalid = |what: &str| invalid(format!("spline \"{}\": {what}", sp.name));
            if let Shape::Band { surface, width, .. } = &sp.shape {
                if self.surface_index(surface).is_none() {
                    return invalid(&format!("no surface named \"{surface}\""));
                }
                if *width < 0.0 {
                    return invalid("negative width");
                }
            }
            if self.material_index(sp.material()).is_none() {
                return invalid(&format!("no material named \"{}\"", sp.material()));
            }
            let styled = match &sp.shape {
                Shape::Band { profile, .. } => self.check_strip_style(sp.style.as_deref(), profile),
                Shape::Wall { model, .. } => {
                    self.check_wall_style(sp.style.as_deref(), model.as_ref())
                }
            };
            if let Err(e) = styled {
                return invalid(&e.to_string());
            }
            if sp.nodes.len() < 2 {
                return invalid("needs at least 2 nodes");
            }
            if sp
                .nodes
                .iter()
                .any(|n| !n.pos.is_finite() || !n.handles.is_valid())
            {
                return invalid("invalid node or handle");
            }
            if sp.resolution < 0.1 {
                return invalid("resolution under 0.1 m");
            }
        }
        for p in &self.props {
            if p.scale.is_nan() || p.scale <= 0.0 {
                return invalid(format!("prop \"{}\": scale must be positive", p.name));
            }
        }
        if let Some(p) = &self.markers.pit
            && (self.road(&p.road).is_none() || p.road == self.main_road)
        {
            return invalid(format!(
                "the pit lane \"{}\" must be a road other than the main road",
                p.road
            ));
        }
        if let Some(r) = &self.reference
            && !(r.width > 0.0
                && r.width.is_finite()
                && r.center.is_finite()
                && r.rotation.is_finite()
                && r.height.is_finite()
                && (0.0..=1.0).contains(&r.opacity))
        {
            return invalid(
                "reference image: the width must be positive and the opacity 0 to 1".into(),
            );
        }
        if self.geo.is_some_and(|g| !g.is_valid()) {
            return invalid("the origin's longitude or latitude is out of range".into());
        }
        if self.surface_index(&self.terrain.surface).is_none()
            || self.material_index(&self.terrain.material).is_none()
        {
            return invalid("terrain: undefined surface or material".into());
        }
        for (i, l) in self.terrain.landforms.iter().enumerate() {
            let finite = match l.kind {
                LandformKind::Raise(h) | LandformKind::Level(h) => h.is_finite(),
            };
            if !(l.center.is_finite()
                && l.to.is_none_or(|t| t.is_finite())
                && l.radius >= 0.0
                && l.falloff >= 0.0
                && finite)
            {
                return invalid(format!(
                    "landform \"{}\": its place, radius and falloff must be numbers, not negative",
                    l.name
                ));
            }
            if self.terrain.landforms[..i].iter().any(|o| o.name == l.name) {
                return invalid(format!("two landforms are named \"{}\"", l.name));
            }
        }
        Ok(())
    }

    fn check_strip_style(&self, style: Option<&str>, profile: &Profile) -> Result<(), Error> {
        if let Some(s) = style
            && !self.strip_styles.iter().any(|t| t.name == s)
        {
            return Err(Error::Invalid(format!("no strip type named \"{s}\"")));
        }
        if let Profile::Shape(points) = profile
            && (points.is_empty()
                || points
                    .iter()
                    .any(|p| !p[0].is_finite() || !p[1].is_finite())
                || points.windows(2).any(|w| w[1][0] < w[0][0]))
        {
            return Err(Error::Invalid(
                "a shaped profile needs points in order across".into(),
            ));
        }
        Ok(())
    }

    fn check_wall_style(&self, style: Option<&str>, model: Option<&ModelRun>) -> Result<(), Error> {
        if let Some(s) = style
            && !self.wall_styles.iter().any(|t| t.name == s)
        {
            return Err(Error::Invalid(format!("no wall type named \"{s}\"")));
        }
        if let Some(m) = model
            && !(m.length >= 0.0 && m.length.is_finite())
        {
            return Err(Error::Invalid(format!(
                "{}: a model's length must be 0 (its own) or more",
                m.model.display()
            )));
        }
        Ok(())
    }

    pub fn strip_style(&self, name: &str) -> Option<&StripStyle> {
        self.strip_styles.iter().find(|s| s.name == name)
    }

    pub fn wall_style(&self, name: &str) -> Option<&WallStyle> {
        self.wall_styles.iter().find(|s| s.name == name)
    }

    pub fn road_index(&self, name: &str) -> Option<usize> {
        self.roads.iter().position(|r| r.name == name)
    }

    pub fn road(&self, name: &str) -> Option<&Road> {
        self.roads.iter().find(|r| r.name == name)
    }

    pub fn spline(&self, name: &str) -> Option<&Spline> {
        self.splines.iter().find(|s| s.name == name)
    }

    /// Nodes of the road or spline named `name`, and whether it is closed.
    pub fn line(&self, name: &str) -> Option<(&[Node], bool)> {
        self.road(name)
            .map(|r| (r.nodes.as_slice(), r.closed))
            .or_else(|| self.spline(name).map(|s| (s.nodes.as_slice(), s.closed)))
    }

    pub fn surface_index(&self, name: &str) -> Option<usize> {
        self.surfaces.iter().position(|s| s.name == name)
    }

    pub fn material_index(&self, name: &str) -> Option<usize> {
        self.materials.iter().position(|m| m.name == name)
    }

    /// Index of the main road; the project must be valid.
    pub fn main_index(&self) -> usize {
        self.road_index(&self.main_road)
            .expect("the main road exists")
    }

    /// Surface of the built-in kind, if the project has one.
    pub fn surface_of(&self, kind: Surface) -> Option<&str> {
        self.surfaces
            .iter()
            .find(|s| s.props.kind == kind)
            .map(|s| s.name.as_str())
    }
}
