//! The editable source of a track: roads as splines with their cross-sections, barriers,
//! markers for the race layout, surfaces and materials. Stored as `project.ron` in the
//! project's directory, next to the textures it uses.
//!
//! Positions are in the simulation's world frame (m, Z up). Places along a road are
//! given as spline parameters `u` (node index plus the fraction of the way to the next
//! node), so that they stay with the road's shape when nodes move.

use std::path::{Path, PathBuf};

use glam::DVec3;
use open_racing_sim::{Surface, SurfaceProps};
use serde::{Deserialize, Serialize};

use crate::Error;

/// Version of `project.ron`.
pub const FORMAT_VERSION: u32 = 1;
pub const PROJECT_FILE: &str = "project.ron";

/// Index into `Project::surfaces`.
pub type SurfaceId = usize;
/// Index into `Project::materials`.
pub type MaterialId = usize;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    pub format: u32,
    pub name: String,
    pub surfaces: Vec<NamedSurface>,
    pub materials: Vec<MaterialDef>,
    pub roads: Vec<Road>,
    /// The circuit: the closed road the centreline, timing and grid follow.
    pub main_road: usize,
    pub markers: Markers,
    pub terrain: Terrain,
}

/// Physical properties of a surface, with a name for the editor.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamedSurface {
    pub name: String,
    pub props: SurfaceProps,
}

/// A tiled, tinted texture with dielectric PBR parameters.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterialDef {
    pub name: String,
    /// sRGB tint multiplied with the texture.
    pub color: [f32; 3],
    pub texture: TextureSource,
    /// Metres one repetition of the texture covers: across and along a road.
    pub tile: [f32; 2],
    pub roughness: f32,
    pub reflectance: f32,
    /// Render back faces too (thin barriers and fences).
    #[serde(default)]
    pub double_sided: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TextureSource {
    /// Plain colour.
    None,
    /// A texture generated by the tool.
    Builtin(BuiltinTexture),
    /// A PNG or DDS file, relative to the project's directory.
    File(PathBuf),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuiltinTexture {
    Asphalt,
    /// Red and white blocks along the kerb, one pair per repetition.
    Kerb,
    Grass,
    Gravel,
    Concrete,
    Armco,
    Paint,
    Dirt,
}

impl BuiltinTexture {
    pub const ALL: [Self; 8] = [
        Self::Asphalt,
        Self::Kerb,
        Self::Grass,
        Self::Gravel,
        Self::Concrete,
        Self::Armco,
        Self::Paint,
        Self::Dirt,
    ];
}

/// A control point of a road. The spline passes through `pos`; `handle` is the offset
/// of its outgoing Bézier handle (the incoming one mirrors it), or `None` to smooth the
/// road through its neighbours automatically.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    pub pos: DVec3,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<DVec3>,
}

impl Node {
    pub fn at(x: f64, y: f64, z: f64) -> Self {
        Self {
            pos: DVec3::new(x, y, z),
            handle: None,
        }
    }
}

/// A value that varies along a road: keys at spline parameters, eased between them. A
/// closed road's value eases from the last key round to the first.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationCurve {
    pub keys: Vec<Key>,
}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Key {
    pub u: f64,
    pub value: f64,
}

impl StationCurve {
    pub fn constant(value: f64) -> Self {
        Self {
            keys: vec![Key { u: 0.0, value }],
        }
    }

    /// The value at `u` on a road whose parameter runs over [0, `period`); closed roads
    /// wrap round, open ones hold their end values.
    pub fn eval(&self, u: f64, period: f64, closed: bool) -> f64 {
        let keys = &self.keys;
        let Some(first) = keys.first() else {
            return 0.0;
        };
        if keys.len() == 1 {
            return first.value;
        }
        // Keys are kept sorted by `u`.
        let last = keys[keys.len() - 1];
        let ease = |a: &Key, b: &Key, u: f64, span: f64| {
            let t = if span > 0.0 {
                (u / span).clamp(0.0, 1.0)
            } else {
                0.0
            };
            a.value + (b.value - a.value) * t * t * (3.0 - 2.0 * t)
        };
        if u < first.u || u >= last.u {
            if !closed {
                return if u < first.u { first.value } else { last.value };
            }
            let span = first.u + period - last.u;
            let from = if u >= last.u {
                u - last.u
            } else {
                u + period - last.u
            };
            return ease(&last, first, from, span);
        }
        let i = keys.partition_point(|k| k.u <= u) - 1;
        let (a, b) = (&keys[i], &keys[i + 1]);
        ease(a, b, u - a.u, b.u - a.u)
    }

    /// Sets the value at `u`, adding a key or moving the one already there.
    pub fn set(&mut self, u: f64, value: f64) {
        match self.keys.iter_mut().find(|k| (k.u - u).abs() < 1e-6) {
            Some(k) => k.value = value,
            None => {
                self.keys.push(Key { u, value });
                self.keys.sort_by(|a, b| a.u.total_cmp(&b.u));
            }
        }
    }
}

/// A stretch of road between two spline parameters. On a closed road `from > to` wraps
/// through the start.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Range {
    pub from: f64,
    pub to: f64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Side {
    Left,
    Right,
}

impl Side {
    /// +1 to the left, −1 to the right.
    pub fn sign(self) -> f64 {
        match self {
            Self::Left => 1.0,
            Self::Right => -1.0,
        }
    }
}

/// Cross-section shape of a strip, from its inner to its outer edge.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub enum Profile {
    /// Continues the plane of what is inside it.
    Flat,
    /// A rounded crown this high (m) in the middle, as on a kerb.
    Crown(f64),
    /// Falls (or rises, negative) this far (m) to the outer edge.
    Slope(f64),
}

/// A band alongside the road: kerb, run-off, gravel trap, grass verge.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Strip {
    pub name: String,
    pub width: f64,
    pub surface: SurfaceId,
    pub material: MaterialId,
    pub profile: Profile,
    /// Where the strip is; everywhere when empty.
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// Metres over which it narrows to nothing at the ends of its ranges.
    #[serde(default)]
    pub fade: f64,
}

/// A painted line on the road, drawn only: it does not change the surface.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaintLine {
    /// Lateral offset of its middle from the road's centre, m, positive to the left.
    pub offset: f64,
    pub width: f64,
    pub material: MaterialId,
    #[serde(default)]
    pub ranges: Vec<Range>,
    /// Painted and gap lengths of a dashed line, m.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dash: Option<(f64, f64)>,
}

/// A wall, guard rail or fence the cars collide with.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Barrier {
    pub name: String,
    pub side: Side,
    /// Distance from the road's edge, m.
    pub offset: f64,
    pub height: f64,
    /// 0 for a thin rail or fence.
    pub thickness: f64,
    pub material: MaterialId,
    #[serde(default)]
    pub ranges: Vec<Range>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Road {
    pub name: String,
    pub closed: bool,
    pub nodes: Vec<Node>,
    /// Distances from the road's centre to its edges, m.
    pub width_left: StationCurve,
    pub width_right: StationCurve,
    /// Banking in radians; positive raises the right edge, as for a left-hand corner.
    pub bank: StationCurve,
    /// Height of the road's centre above its edges, m, for drainage.
    pub crown: f64,
    pub surface: SurfaceId,
    pub material: MaterialId,
    /// Strips outside each edge, from the road outwards.
    pub left: Vec<Strip>,
    pub right: Vec<Strip>,
    pub lines: Vec<PaintLine>,
    pub barriers: Vec<Barrier>,
    /// Spacing of the cross-sections the road is built from, m.
    pub resolution: f64,
}

impl Road {
    /// Number of spline segments.
    pub fn segments(&self) -> usize {
        match (self.nodes.len(), self.closed) {
            (0 | 1, _) => 0,
            (n, true) => n,
            (n, false) => n - 1,
        }
    }

    /// Range of the spline parameter: [0, period].
    pub fn period(&self) -> f64 {
        self.segments() as f64
    }

    pub fn strips(&self, side: Side) -> &Vec<Strip> {
        match side {
            Side::Left => &self.left,
            Side::Right => &self.right,
        }
    }

    /// Inserts a node before `index`, keeping keys and ranges where they were on the
    /// road.
    pub fn insert_node(&mut self, index: usize, node: Node) {
        self.nodes.insert(index, node);
        self.shift_params(index as f64 - 1.0, 1.0);
    }

    /// Removes a node, keeping keys and ranges where they were on the road as far as
    /// possible.
    pub fn remove_node(&mut self, index: usize) {
        self.nodes.remove(index);
        self.shift_params(index as f64, -1.0);
    }

    /// Moves every parameter beyond `after` by `by`.
    fn shift_params(&mut self, after: f64, by: f64) {
        let period = self.period().max(1.0);
        let shift = |u: &mut f64| {
            if *u > after {
                *u = (*u + by).clamp(0.0, period);
            }
        };
        for c in [&mut self.width_left, &mut self.width_right, &mut self.bank] {
            c.keys.iter_mut().for_each(|k| shift(&mut k.u));
        }
        let ranges = self
            .left
            .iter_mut()
            .chain(self.right.iter_mut())
            .flat_map(|s| s.ranges.iter_mut())
            .chain(self.barriers.iter_mut().flat_map(|b| b.ranges.iter_mut()))
            .chain(self.lines.iter_mut().flat_map(|l| l.ranges.iter_mut()));
        for r in ranges {
            shift(&mut r.from);
            shift(&mut r.to);
        }
    }
}

/// Where a race is run: the start/finish line, sector boundaries, grid and pit lane.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Markers {
    /// Start/finish line on the main road.
    pub start: f64,
    /// Sector boundaries on the main road.
    pub sectors: Vec<f64>,
    pub grid: Grid,
    pub pit: Option<Pit>,
}

/// Grid slots generated behind the start line.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Grid {
    pub count: usize,
    /// Distance between consecutive slots, m.
    pub spacing: f64,
    /// Lateral offset of each slot from the middle, alternating sides, m.
    pub stagger: f64,
    /// Distance from the start line to the pole slot, m.
    pub behind: f64,
    /// Side of the pole slot.
    pub pole: Side,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pit {
    /// The pit lane's road; it starts where the lane leaves the track and ends where it
    /// rejoins.
    pub road: usize,
    /// Speed limit, m/s.
    pub speed_limit: f64,
    /// Pit boxes on the pit road.
    pub boxes: Vec<f64>,
    pub box_side: Side,
    /// Lateral offset of the boxes from the lane's centre, m.
    pub box_offset: f64,
}

/// Ground around the roads, shaped to meet their outer edges.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Terrain {
    pub enabled: bool,
    pub surface: SurfaceId,
    pub material: MaterialId,
    /// How far beyond the roads it extends, m.
    pub margin: f64,
    /// Size of its grid cells, m.
    pub cell: f64,
}

impl Project {
    /// A new project with the built-in surfaces and materials and a small oval to start
    /// from.
    pub fn new(name: &str) -> Self {
        let surfaces = crate::builtin::surfaces();
        let materials = crate::builtin::materials();
        let s = |name: &str| surfaces.iter().position(|x| x.name == name).unwrap();
        let m = |name: &str| materials.iter().position(|x| x.name == name).unwrap();
        // A rounded rectangle, 600 m × 250 m, driven anticlockwise.
        let nodes = [
            (0.0, 0.0),
            (250.0, 0.0),
            (420.0, 20.0),
            (480.0, 130.0),
            (420.0, 240.0),
            (250.0, 260.0),
            (0.0, 260.0),
            (-120.0, 200.0),
            (-150.0, 130.0),
            (-120.0, 60.0),
        ]
        .map(|(x, y)| Node::at(x, y, 0.0))
        .to_vec();
        // Kerbs through the corners.
        let corners = vec![Range { from: 1.6, to: 4.4 }, Range { from: 6.6, to: 9.4 }];
        let kerb = Strip {
            name: "kerb".into(),
            width: 1.2,
            surface: s("kerb"),
            material: m("kerb"),
            profile: Profile::Crown(0.03),
            ranges: corners,
            fade: 4.0,
        };
        let grass = |width| Strip {
            name: "grass".into(),
            width,
            surface: s("grass"),
            material: m("grass"),
            profile: Profile::Slope(0.3),
            ranges: vec![],
            fade: 0.0,
        };
        let barrier = |side| Barrier {
            name: "wall".into(),
            side,
            offset: 20.0,
            height: 1.0,
            thickness: 0.5,
            material: m("concrete"),
            ranges: vec![],
        };
        let road = Road {
            name: "circuit".into(),
            closed: true,
            nodes,
            width_left: StationCurve::constant(6.0),
            width_right: StationCurve::constant(6.0),
            bank: StationCurve::constant(0.0),
            crown: 0.05,
            surface: s("asphalt"),
            material: m("asphalt"),
            left: vec![kerb.clone(), grass(18.0)],
            right: vec![kerb, grass(18.0)],
            lines: [5.7, -5.7]
                .map(|offset| PaintLine {
                    offset,
                    width: 0.12,
                    material: m("paint"),
                    ranges: vec![],
                    dash: None,
                })
                .to_vec(),
            barriers: vec![barrier(Side::Left), barrier(Side::Right)],
            resolution: 2.0,
        };
        Self {
            format: FORMAT_VERSION,
            name: name.into(),
            terrain: Terrain {
                enabled: true,
                surface: s("grass"),
                material: m("grass"),
                margin: 200.0,
                cell: 8.0,
            },
            surfaces,
            materials,
            roads: vec![road],
            main_road: 0,
            markers: Markers {
                start: 0.5,
                sectors: vec![3.0, 6.5],
                grid: Grid {
                    count: 12,
                    spacing: 8.0,
                    stagger: 2.5,
                    behind: 10.0,
                    pole: Side::Left,
                },
                pit: None,
            },
        }
    }

    pub fn load(dir: &Path) -> Result<Self, Error> {
        let path = dir.join(PROJECT_FILE);
        let src = std::fs::read_to_string(&path).map_err(|e| Error::Io(path.clone(), e))?;
        let project: Self = ron::from_str(&src).map_err(|e| Error::Parse(path.clone(), Box::new(e)))?;
        if project.format != FORMAT_VERSION {
            return Err(Error::Invalid(format!(
                "{}: format version {}, expected {FORMAT_VERSION}",
                path.display(),
                project.format
            )));
        }
        project.validate()?;
        Ok(project)
    }

    pub fn save(&self, dir: &Path) -> Result<(), Error> {
        std::fs::create_dir_all(dir).map_err(|e| Error::Io(dir.to_path_buf(), e))?;
        let src = ron::ser::to_string_pretty(self, ron::ser::PrettyConfig::default())
            .expect("project serialises");
        let path = dir.join(PROJECT_FILE);
        std::fs::write(&path, src).map_err(|e| Error::Io(path, e))
    }

    /// Checks that every index refers to something that exists and the main road can be
    /// a circuit.
    pub fn validate(&self) -> Result<(), Error> {
        let invalid = |msg: String| Err(Error::Invalid(msg));
        let (ns, nm) = (self.surfaces.len(), self.materials.len());
        let Some(main) = self.roads.get(self.main_road) else {
            return invalid("the main road does not exist".into());
        };
        if !main.closed || main.nodes.len() < 3 {
            return invalid(format!(
                "the main road \"{}\" must be a closed loop of at least 3 nodes",
                main.name
            ));
        }
        for r in &self.roads {
            let strips = r.left.iter().chain(&r.right);
            let surfaces = std::iter::once(r.surface).chain(strips.clone().map(|s| s.surface));
            let materials = [r.material]
                .into_iter()
                .chain(strips.map(|s| s.material))
                .chain(r.lines.iter().map(|l| l.material))
                .chain(r.barriers.iter().map(|b| b.material));
            if surfaces.clone().any(|s| s >= ns) {
                return invalid(format!("road \"{}\": undefined surface", r.name));
            }
            if materials.clone().any(|m| m >= nm) {
                return invalid(format!("road \"{}\": undefined material", r.name));
            }
            if r.nodes.len() < 2 {
                return invalid(format!("road \"{}\" needs at least 2 nodes", r.name));
            }
            if r.resolution <= 0.1 {
                return invalid(format!("road \"{}\": resolution too fine", r.name));
            }
        }
        if let Some(p) = &self.markers.pit
            && (p.road >= self.roads.len() || p.road == self.main_road)
        {
            return invalid("the pit lane must be a road other than the main road".into());
        }
        if self.terrain.surface >= ns || self.terrain.material >= nm {
            return invalid("terrain: undefined surface or material".into());
        }
        Ok(())
    }

    /// Surface of the built-in kind, if the project has one.
    pub fn surface_of(&self, kind: Surface) -> Option<SurfaceId> {
        self.surfaces.iter().position(|s| s.props.kind == kind)
    }
}
